language: node_js
node_js: "12"
cache:
  yarn: true

install:
  - yarn

script:
  - yarn ci:lint
  - yarn ci:test
  - yarn ci:sonar

deploy:
  provider: script
  script: echo DEPLOY
  skip_cleanup: true
  on:
    branch: master
